# Generated by Django 5.2.12 on 2026-03-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_activity_company_activity_is_system_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("concerned", "Concerned"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="transcript",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="employee_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="at_risk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deal",
            name="close_probability",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="deal",
            name="health_score",
            field=models.IntegerField(default=50),
        ),
    ]
